# Application
app.name = "Parking Payment Service"
app.version = "1.0.0"

play.http.secret.key = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"

# Server
play.server.http.port = 9000

#Security
play.filters.hosts.allowed = ["localhost:9000", "127.0.0.1:9000"]
play.filters.disabled += "play.filters.csrf.CSRFFilter"


# Database
slick.dbs.default.profile = "slick.jdbc.MySQLProfile$"
slick.dbs.default.db.driver = "com.mysql.cj.jdbc.Driver"
slick.dbs.default.db.url = "jdbc:mysql://localhost:3306/scala-parking-payment-service"
slick.dbs.default.db.user = "root"
slick.dbs.default.db.password = "root"

# Connection pool
slick.dbs.default.db.numThreads = 5
slick.dbs.default.db.maxConnections = 5
slick.dbs.default.db.minConnections = 2

# Evolutions
play.evolutions.db.default.enabled = true
play.evolutions.db.default.autoApply = true
